### ISSUE TITLE
Can't make simple echo server work over multiple invocations.

### ISSUE THREAD

**Issue by angerman** [hargettp/courier#10]
Trying to debug an issue I'm having where running a "server" and connecting to it multiple times, I came up with the following simple echo server / client:

https://gist.github.com/angerman/b541ae09155d8a460648

```
$ courier-echo server & # works
$ courier-echo client   # works
$ courier-echo client   # doesn't work any more.
```

somewhere between the first and second invocation of `client`, the server just stalls. Please tell me I did something fundamentally wrong!

**Comment by hargettp** [comment]
I haven't forgotten this one.  Sadly, I've come to the conclusion my connection handling logic is completely broken, so it needs a bit of a rethink.  Hence the delay. Apologies.

**Comment by angerman** [comment]
No worries.
